In [1]:
import pandas as pd
import numpy as np
import os
pd.set_option('display.max_columns', 1000)

In [2]:
os.chdir("G:\\Network Attacks")

In [3]:
train=pd.read_csv("train_data.csv")
test=pd.read_csv("test_data.csv")

In [4]:
print('The train data has {} rows and {} columns'.format(train.shape[0], train.shape[1]))
print('The test data has {} rows and {} columns'.format(test.shape[0],test.shape[1]))

The train data has 169307 rows and 43 columns
The test data has 91166 rows and 42 columns


In [5]:
train['target'].value_counts(normalize=True)

0    0.583957
2    0.217676
1    0.198367
Name: target, dtype: float64

In [6]:
train.head()

connection_id  cont_1  cont_2  cont_3  cont_4  cont_5  cont_6  cont_7  \
0       cxcon_1       0    1032       0     0.0     0.0     0.0     0.0   
1       cxcon_4       0     520       0     0.0     0.0     0.0     0.0   
2       cxcon_7       0    1032       0     0.0     0.0     0.0     0.0   
3      cxcon_10       0    1032       0     0.0     0.0     0.0     0.0   
4      cxcon_13       0    1032       0     0.0     0.0     0.0     0.0   

   cont_8  cont_9  cont_10  cont_11  cont_12  cont_13  cont_14  cont_15  \
0     1.0     0.0      0.0      1.0      0.0      1.0      0.0      0.0   
1     1.0     0.0      0.0      1.0      0.0      1.0      0.0      0.0   
2     1.0     0.0      0.0      1.0      0.0      1.0      0.0      0.0   
3     1.0     0.0      0.0      1.0      0.0      1.0      0.0      0.0   
4     1.0     0.0      0.0      1.0      0.0      1.0      0.0      0.0   

   cont_16  cont_17  cont_18  cat_1  cat_2  cat_3  cat_4  cat_5  cat_6  cat_7  \
0      0.0      0.0      0.0      3     10      1      0      0      0      0   
1      0.0      0.0      0.0      3     10      1      0      0      0      0   
2      0.0      0.0      0.0      3     10      1      0      0      0      0   
3      0.0      0.0      0.0      3     10      1      0      0      0      0   
4      0.0      0.0      0.0      3     10      1      0      0      0      0   

   cat_8  cat_9  cat_10  cat_11  cat_12  cat_13  cat_14  cat_15  cat_16  \
0      0      0       0       0       0       0       0       0       0   
1      0      0       0       0       0       0       0       0       0   
2      0      0       0       0       0       0       0       0       0   
3      0      0       0       0       0       0       0       0       0   
4      0      0       0       0       0       0       0       0       0   

   cat_17  cat_18  cat_19  cat_20  cat_21  cat_22  cat_23  target  
0       0       0       0     511     511     255     255       2  
1       0       0       0     511     511     255     255       0  
2       0       0       0     511     511     255     255       0  
3       0       0       0     511     511     255     255       0  
4       0       0       0     511     511     255     255       2

In [7]:
train.isnull().sum(axis=0)

connection_id    0
cont_1           0
cont_2           0
cont_3           0
cont_4           0
cont_5           0
cont_6           0
cont_7           0
cont_8           0
cont_9           0
cont_10          0
cont_11          0
cont_12          0
cont_13          0
cont_14          0
cont_15          0
cont_16          0
cont_17          0
cont_18          0
cat_1            0
cat_2            0
cat_3            0
cat_4            0
cat_5            0
cat_6            0
cat_7            0
cat_8            0
cat_9            0
cat_10           0
cat_11           0
cat_12           0
cat_13           0
cat_14           0
cat_15           0
cat_16           0
cat_17           0
cat_18           0
cat_19           0
cat_20           0
cat_21           0
cat_22           0
cat_23           0
target           0
dtype: int64

# Model 1 

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import confusion_matrix

In [9]:
feature_names = [x for x in train.columns if x not in ['connection_id','target']]
target = train['target']
feature_names

['cont_1',
 'cont_2',
 'cont_3',
 'cont_4',
 'cont_5',
 'cont_6',
 'cont_7',
 'cont_8',
 'cont_9',
 'cont_10',
 'cont_11',
 'cont_12',
 'cont_13',
 'cont_14',
 'cont_15',
 'cont_16',
 'cont_17',
 'cont_18',
 'cat_1',
 'cat_2',
 'cat_3',
 'cat_4',
 'cat_5',
 'cat_6',
 'cat_7',
 'cat_8',
 'cat_9',
 'cat_10',
 'cat_11',
 'cat_12',
 'cat_13',
 'cat_14',
 'cat_15',
 'cat_16',
 'cat_17',
 'cat_18',
 'cat_19',
 'cat_20',
 'cat_21',
 'cat_22',
 'cat_23']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(train,target,train_size=0.7,stratify=target,test_size=0.3,random_state=2017)

In [11]:
clf1 = DecisionTreeClassifier(max_depth=8, min_samples_split = 7, max_features = 'sqrt')

In [12]:
## Train model
clf1.fit(train[feature_names], target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=8,
            max_features='sqrt', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=7,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [13]:
#prediction on test
pred1=clf1.predict(test[feature_names])

In [14]:
clf1_accu= cross_val_score(clf1, train[feature_names],target, cv=5, scoring='accuracy')
clf1_accu

array([ 0.78049141,  0.77922155,  0.7788967 ,  0.77865391,  0.77962197])

In [15]:
##make submission
sub=pd.read_csv("sample_submission.csv")
sub['target'] = pred1
sub['target'] = sub['target'].astype(int)
sub.to_csv('sub1.csv', index=False)

In [24]:
##function for multi_accuracy
#from sklearn.metrics import accuracy_score
#def multAcc(pred, train):
 #   label=train.get_label()
  #  acc = accuracy_score(label,pred)
   # return 'maccuracy', 
   # acc


# Model2

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import make_scorer

In [16]:
clf2 = OneVsRestClassifier(LogisticRegression())

In [17]:
clf2.fit(train[feature_names],target)

OneVsRestClassifier(estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
          n_jobs=1)

In [63]:
pred2=clf2.predict(test[feature_names])
pred2

array([1, 0, 0, ..., 0, 1, 1], dtype=int64)

In [64]:
##make submission
sub=pd.read_csv("sample_submission.csv")
sub['target'] = pred2
sub['target'] = sub['target'].astype(int)
sub.to_csv('sub2.csv', index=False)

In [93]:
clf2_accu= cross_val_score(clf2, train[feature_names],target, cv=5, scoring='accuracy')
clf2_accu

array([ 0.77095269,  0.77234068,  0.77089363,  0.77153658,  0.77061429])

# Model3

In [22]:
import lightgbm as lgb

In [32]:
X_train[feature_names]

cont_1  cont_2  cont_3  cont_4  cont_5  cont_6  cont_7  cont_8  \
153403       0    1032       0     0.0     0.0     0.0     0.0    1.00   
33773        0    1032       0     0.0     0.0     0.0     0.0    1.00   
47698        0    1032       0     0.0     0.0     0.0     0.0    1.00   
106540       0    1032       0     0.0     0.0     0.0     0.0    1.00   
21830        0       0       0     1.0     1.0     0.0     0.0    0.03   
148690       0     520       0     0.0     0.0     0.0     0.0    1.00   
5595         0    1032       0     0.0     0.0     0.0     0.0    1.00   
120826       0       0       0     1.0     1.0     0.0     0.0    0.00   
74750        0     520       0     0.0     0.0     0.0     0.0    1.00   
87690        0    1032       0     0.0     0.0     0.0     0.0    1.00   
75081        0    1032       0     0.0     0.0     0.0     0.0    1.00   
1653         0    1032       0     0.0     0.0     0.0     0.0    1.00   
124888       0       0       0     1.0     1.0     0.0     0.0    0.01   
158521       0    1032       0     0.0     0.0     0.0     0.0    1.00   
82876        0    1032       0     0.0     0.0     0.0     0.0    1.00   
88557        0    1032       0     0.0     0.0     0.0     0.0    1.00   
6876         0     520       0     0.0     0.0     0.0     0.0    1.00   
123863       0    1032       0     0.0     0.0     0.0     0.0    1.00   
15314        4      28      93     0.0     0.0     0.0     0.0    1.00   
43771     7804     147     105     0.0     0.0     0.0     0.0    1.00   
40846        0       0       0     1.0     1.0     0.0     0.0    0.27   
80777        0       0       0     0.0     0.0     1.0     1.0    0.06   
143425       0    1032       0     0.0     0.0     0.0     0.0    1.00   
83072        0       0       0     1.0     1.0     0.0     0.0    0.08   
21005        0    1032       0     0.0     0.0     0.0     0.0    1.00   
151922       0     520       0     0.0     0.0     0.0     0.0    1.00   
102328       0     207    2561     0.0     0.0     0.0     0.0    1.00   
128687       0       0       0     1.0     1.0     0.0     0.0    0.06   
92132        0     520       0     0.0     0.0     0.0     0.0    1.00   
27223        0     105     147     0.0     0.0     0.0     0.0    1.00   
...        ...     ...     ...     ...     ...     ...     ...     ...   
93097        0    1032       0     0.0     0.0     0.0     0.0    1.00   
144860       0       0       0     1.0     1.0     0.0     0.0    0.04   
129317       0    1032       0     0.0     0.0     0.0     0.0    1.00   
152344       0     728     331     0.0     0.0     0.0     0.0    1.00   
131269       0    1032       0     0.0     0.0     0.0     0.0    1.00   
53680        0    1032       0     0.0     0.0     0.0     0.0    1.00   
46814        0       0       0     0.0     0.0     1.0     1.0    0.02   
154650       0       0       0     1.0     1.0     0.0     0.0    0.01   
45273        0    1032       0     0.0     0.0     0.0     0.0    1.00   
44181        0     520       0     0.0     0.0     0.0     0.0    1.00   
126939       0     520       0     0.0     0.0     0.0     0.0    1.00   
122700       0     520       0     0.0     0.0     0.0     0.0    1.00   
19598        0       0       0     1.0     1.0     0.0     0.0    0.05   
100809       0      43     126     0.0     0.0     0.0     0.0    1.00   
153121       0       0       0     1.0     1.0     0.0     0.0    0.07   
167554       0    1032       0     0.0     0.0     0.0     0.0    1.00   
101465       0       0       0     0.0     0.0     1.0     1.0    1.00   
132192       0    1032       0     0.0     0.0     0.0     0.0    1.00   
38375        0    1032       0     0.0     0.0     0.0     0.0    1.00   
28572        0     249    3631     0.0     0.0     0.0     0.0    1.00   
24553        0     520       0     0.0     0.0     0.0     0.0    1.00   
158136       0      44      74     0.0     0.0     0.0     0.0    0.98   
59593       

In [36]:
X_train_int = X_train[feature_names].apply(pd.to_numeric, downcast='integer')

In [37]:
y_train_int = y_train.apply(pd.to_numeric,downcast='integer')

In [38]:
X_test_int = X_test[feature_names].apply(pd.to_numeric, downcast='integer')

In [39]:
y_test_int = y_test.apply(pd.to_numeric, downcast='integer' )

In [40]:
d_train = lgb.Dataset(X_train_int, y_train_int)
dval = lgb.Dataset(X_test_int, y_test_int)

In [41]:
d_train

In [47]:
params = {
    
    'num_leaves' : 256,
    'learning_rate':0.03,
    'metric':'multi_error',
    'objective':'multiclass',
    'num_class': 3,
    'early_stopping_round': 40,
    'max_depth':10,
    'bagging_fraction':0.5,
    'feature_fraction':0.6,
    'bagging_seed':2017,
    'feature_fraction_seed':2017,
    'verbose' : 1
    
    
}

In [48]:
lgb_cv = lgb.cv(params, d_train, num_boost_round=500, nfold= 5, shuffle=True, stratified=True, verbose_eval=20)

C:\ProgramData\Anaconda3\lib\site-packages\lightgbm\engine.py:393: UserWarning: Found `early_stopping_round` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))


[20]	cv_agg's multi_error: 0.219493 + 0.000131908
[40]	cv_agg's multi_error: 0.219383 + 0.000198671
[60]	cv_agg's multi_error: 0.219307 + 0.000231966
[80]	cv_agg's multi_error: 0.219206 + 0.00017827
[100]	cv_agg's multi_error: 0.219223 + 0.000149351


# Model 4